version: '3'

services:
  # Go Application
  go-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      finews_network:
        ipv4_address: 172.16.238.10

  # Redis Server
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      finews_network:
        ipv4_address: 172.16.238.20

networks:
  finews_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
